### ISSUE TITLE
Dummy ticket 22

### ISSUE THREAD

**Issue by juanludlf** [isa-group/aml#22]

**Comment by benavidescuevas** [comment]
Me han llegado como 30 correos sobre apertura y cierres de tickets. No sé si puedo hacerlo yo solo pero, sería mejor que me lleguen esos correos. Si puedes hacer algo...

**Comment by juanludlf** [comment]
Siento el reciente spam. Aprovecho para avisar que debéis quitar la suscripción o cambiarla al método de "ser notificado solo en participaciones o menciones" en el GitHub del grupo "isa-group". Durante la migración de Redmine a GitHub, se abrirán alrededor de 93 issues solo para AML. En la migración de IDEAS serán alrededor de 276, por lo que os aconsejo actualizar el estado de suscripción.
Muchas gracias, y perdón nuevamente por el spam.
Un saludo,
Juanlu
